### ISSUE TITLE
Kinematics controller implementation

### ISSUE THREAD

**Issue by andreucm** [JavierRubia/Garrinator#6]
Hi @JavierRubia 

At branch https://github.com/JavierRubia/Garrinator/tree/omni_4_controller, you can see the basic skeleton for the controller. 

Please keep in mind that the main function of this controller is to implement the inverse kinematics, so to translate from a twist to joint angular speeds. 

The controller is not finished, it is your turn !  Feel free to use the same branch to develop. 

As an additional sources of inspiration, you can use: 
- http://wiki.ros.org/ros_control/Tutorials/Writing%20a%20new%20controller
- https://subscription.packtpub.com/book/hardware_and_creative/9781788478953/8/ch08lvl1sec72/writing-a-basic-joint-controller-in-ros

and googling appropiately. 

Once you make some progress and fight a little, you can come back to me to discuss the last details. 

Good luck !!

Andreu

**Comment by JavierRubia** [comment]
Hi @andreucm 

At branch https://github.com/JavierRubia/Garrinator/tree/omni_4_controller, there is an error that keeps popping up, I've done some research and seems something related with plugin lib and multiple libraries, right after launching the Omni4_Controller the following error appears:

`[ERROR] [1590064070.480740842]: Could not load class 'omni4_controller/Omni4Controller': MultiLibraryClassLoader: Could not create object of class type omni4_controller::Omni4Controller as no factory exists for it. Make sure that the library exists and was explicitly loaded through MultiLibraryClassLoader::loadLibrary()`

`[ERROR] [1590064070.482817591]: Could not load controller 'omni4_controller' because controller type 'omni4_controller/Omni4Controller' does not exist.`

`[ERROR] [1590064070.482877323]: Use 'rosservice call controller_manager/list_controller_types' to get the available types`

`[ERROR] [1590064071.484603]: Failed to load omni4_controller`

While the Omni4_controller is launch I've typed the following:
Input:
`rosservice call /controller_manager/list_controllers `
Output:
`controller: [ ]`

So after that, I've stopped the program and checked if there was the controller and typed the following:
input:
`rospack plugins --attrib=plugin controller_interface `

Output: (among many other controllers as velocity_controllers, effort_controllers, ...)
`omni4_controller /home/javier/catkin_ws/src/Garrinator/omni4_controller/controller_plugins.xml`

I've checked every step in the book that was recommended to create the controller and there is no difference between the book and our code.

Do you have any clue of why this error appears?

Thank you.

Javier Rubia

**Comment by andreucm** [comment]
Hi @JavierRubia , please pull and test. Thanks!
